### PR TITLE
Migrated the metadata into `pyproject.toml`.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by thatch** [comment]
I think this means we'll drop python 3.6 compatibility because the version of setuptools that supports pep621 is `>=3.7` but I can fix that in a subsequent commit because it will need changes to the GH Actions as well.

**Comment by kurtmckee** [comment]
If poetry is used there's no need to drop Python 3.6 yet.

I'm rebasing for #46 and I'm not sure how to conveniently build regexlint without a `setup.py` file now. tox is still able to build the project but I haven't figured out how to do it manually (i.e. `poetry build` and `flit build` fail, and I can't run `python setup.py sdist` anymore).

What's the recommended way to build the project?

**Comment by KOLANICH** [comment]
>I think this means we'll drop python 3.6 compatibility because the version of setuptools that supports pep621 is >=3.7

No, this metadata specifies the verion of python to which pip will allow installation of a prebuilt wheel (asumming that the code inside the wheel will not work on other versions), it also affects fetching from pypi.

If a certain version of `setuptools` has dropped support of a certain version of python, it only means that building wheels using that version of python and setuptools is unsupported. It doesn't mean that  a wheel built using the machine with later versions cannot be installed on machines with earlier versions.

So specifying that the package needs a version of python higher than it actually needs to run is unjustified.

**Comment by thatch** [comment]
> What's the recommended way to build the project?

https://pypi.org/project/build/ or `pip install .`

**Comment by KOLANICH** [comment]
>What's the recommended way to build the project?

I personally do the following:

```bash
rm -rf ./build ./dist
python3 -m build -nwx
sudo pip3 install --upgrade ./dist/*.whl
```

**Comment by thatch** [comment]
> > I think this means we'll drop python 3.6 compatibility because the version of setuptools that supports pep621 is >=3.7
> 
> No, this metadata specifies the verion of python to which pip will allow installation of a prebuilt wheel (asumming that the code inside the wheel will not work on other versions), it also affects fetching from pypi.

That requires me to upload a wheel (which I'm doing) and all my users to use a wheel (which I know they don't; my workplace builds from sdist).  I think it's fairer to specify the min version of 3.7 because I know you can't build from the sdist on 3.6 anymore , or more likely I'll just switch it to flit before the next release.

**Comment by KOLANICH** [comment]
1. `flit_core` supports `3.6`
2. `flit_core` (and build packends in general) have own `requires-python`.

**Pull request merged**
